{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lefu.ppbluetoothkit",
    "module": "ppbluetoothkit",
    "version": "4.2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "ppbluetoothkit-4.2.0.1.aar",
          "url": "ppbluetoothkit-4.2.0.1.aar",
          "size": 662013,
          "sha512": "f65d702dd96e6e0b7473c7622c70879bb0aaa0158a993e38dcd00c73e507f3f651929d421ef1cf15f445152d1a42a19bb945eabcc976eab692b8167055e8002b",
          "sha256": "e2d5754b5a4786322dfd2ada4eb02b5b88ab94de382e755270fa5068b096c3f3",
          "sha1": "a1f10e59730df096edea0504d8aee9da1076883a",
          "md5": "425af08c756dc466dd1b2e08a599f3ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "ppbluetoothkit-4.2.0.1.aar",
          "url": "ppbluetoothkit-4.2.0.1.aar",
          "size": 662013,
          "sha512": "f65d702dd96e6e0b7473c7622c70879bb0aaa0158a993e38dcd00c73e507f3f651929d421ef1cf15f445152d1a42a19bb945eabcc976eab692b8167055e8002b",
          "sha256": "e2d5754b5a4786322dfd2ada4eb02b5b88ab94de382e755270fa5068b096c3f3",
          "sha1": "a1f10e59730df096edea0504d8aee9da1076883a",
          "md5": "425af08c756dc466dd1b2e08a599f3ed"
        }
      ]
    }
  ]
}
