{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lefu.ppbluetoothkit",
    "module": "ppbluetoothkit",
    "version": "4.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ppbluetoothkit-4.5.0.aar",
          "url": "ppbluetoothkit-4.5.0.aar",
          "size": 858558,
          "sha512": "514fe0290ffdc6225f9a9727db686ec0be673c5661826e18bf66164101e0a4134548e2e0dadfd75e03fad220f7874d44398193f4126e91c80c82b267af907ae9",
          "sha256": "a16b90aa55f54567ea9ca522d67b7d47a72243bb77b65050c09a3b20158e8e69",
          "sha1": "d1a7aeab478549cdcbf8ee482c920dcc397bc62f",
          "md5": "c4c6b5772345198c91c97acafa232248"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ppbluetoothkit-4.5.0.aar",
          "url": "ppbluetoothkit-4.5.0.aar",
          "size": 858558,
          "sha512": "514fe0290ffdc6225f9a9727db686ec0be673c5661826e18bf66164101e0a4134548e2e0dadfd75e03fad220f7874d44398193f4126e91c80c82b267af907ae9",
          "sha256": "a16b90aa55f54567ea9ca522d67b7d47a72243bb77b65050c09a3b20158e8e69",
          "sha1": "d1a7aeab478549cdcbf8ee482c920dcc397bc62f",
          "md5": "c4c6b5772345198c91c97acafa232248"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ppbluetoothkit-4.5.0-sources.jar",
          "url": "ppbluetoothkit-4.5.0-sources.jar",
          "size": 571899,
          "sha512": "1cea4ca9e1351d3eb50aa6d2f3e8ac20f3980565b4e20887768412fd98c8d2208f8c058091159e5b728ab4f1262bf31c2a8690cc72c10975081b44af4d7b3c42",
          "sha256": "4e5905059132c862eb483442db5f86daed5d71fabaa9180cb3c6ea3b0312fac7",
          "sha1": "410acbb04b99b9d2e9c0f1dc23b64fc8093b6312",
          "md5": "51c212f3688744faf7cab0ee7d519fa8"
        }
      ]
    }
  ]
}
