{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lefu.ppbasekit",
    "module": "ppbasekit",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "ppbasekit-4.2.0.aar",
          "url": "ppbasekit-4.2.0.aar",
          "size": 239088,
          "sha512": "78375f169440070f0759f24a6b9a97b835a8d443dfec497d4251996780bbc30088dfa05b4f58a43df3fdf5590da85beabd78d21e122eec11935b063f9f233bd3",
          "sha256": "a855a79a0a84fdaeffaa170a1bcdf0fb1faad63bf2d78bddbe37087b915aecfc",
          "sha1": "003aff9fba368dcf3e6409cee8065eb4136dcd61",
          "md5": "8ffcb0962116e52d5ef5a854201881fe"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "PPBluetoothKitDemo.ppsdkkit.lefulib",
          "module": "lfgson",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "ppbasekit-4.2.0.aar",
          "url": "ppbasekit-4.2.0.aar",
          "size": 239088,
          "sha512": "78375f169440070f0759f24a6b9a97b835a8d443dfec497d4251996780bbc30088dfa05b4f58a43df3fdf5590da85beabd78d21e122eec11935b063f9f233bd3",
          "sha256": "a855a79a0a84fdaeffaa170a1bcdf0fb1faad63bf2d78bddbe37087b915aecfc",
          "sha1": "003aff9fba368dcf3e6409cee8065eb4136dcd61",
          "md5": "8ffcb0962116e52d5ef5a854201881fe"
        }
      ]
    }
  ]
}
