{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lefu.ppbasekit",
    "module": "ppbasekit",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "ppbasekit-4.2.0.aar",
          "url": "ppbasekit-4.2.0.aar",
          "size": 239088,
          "sha512": "f1be961c61c33f1760b7a0cbb07a6a6f2c8640e160dcbe6e8ebb7e9f87b6befe75471378547f6976a84d282ef1f82c4ec32af84baa460e91407aafb56f0f7714",
          "sha256": "11bf2791732d6409ca6e84dd6f15d5830c71fb1723b2754c4471fd18e8e601af",
          "sha1": "b113aa7510b326601f106cf97ff6f8336e5885fa",
          "md5": "999fd00db84e5a1edc13545fe00bb19d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "ppbasekit-4.2.0.aar",
          "url": "ppbasekit-4.2.0.aar",
          "size": 239088,
          "sha512": "f1be961c61c33f1760b7a0cbb07a6a6f2c8640e160dcbe6e8ebb7e9f87b6befe75471378547f6976a84d282ef1f82c4ec32af84baa460e91407aafb56f0f7714",
          "sha256": "11bf2791732d6409ca6e84dd6f15d5830c71fb1723b2754c4471fd18e8e601af",
          "sha1": "b113aa7510b326601f106cf97ff6f8336e5885fa",
          "md5": "999fd00db84e5a1edc13545fe00bb19d"
        }
      ]
    }
  ]
}
