{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lefu.ppbluetoothkit",
    "module": "ppbluetoothkit",
    "version": "4.5.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ppbluetoothkit-4.5.1.aar",
          "url": "ppbluetoothkit-4.5.1.aar",
          "size": 860428,
          "sha512": "620f1f5ee36ddb80483468dcfd15e8e1c6b45cde404ab50d6bab4845c54139bfc42fe009bf87918343f5d780d34939b221f12e7bfd949b8367035e7aa4cd3dd7",
          "sha256": "2a48bf47bd55f4e5b9ce3f81609cf91b03560e6cd69a005f40ea3fa6f823193b",
          "sha1": "232b2773cf53a5f0b529e8f2054eb7d0e41cd83e",
          "md5": "987e62526311df58e97653933bb89341"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ppbluetoothkit-4.5.1.aar",
          "url": "ppbluetoothkit-4.5.1.aar",
          "size": 860428,
          "sha512": "620f1f5ee36ddb80483468dcfd15e8e1c6b45cde404ab50d6bab4845c54139bfc42fe009bf87918343f5d780d34939b221f12e7bfd949b8367035e7aa4cd3dd7",
          "sha256": "2a48bf47bd55f4e5b9ce3f81609cf91b03560e6cd69a005f40ea3fa6f823193b",
          "sha1": "232b2773cf53a5f0b529e8f2054eb7d0e41cd83e",
          "md5": "987e62526311df58e97653933bb89341"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ppbluetoothkit-4.5.1-sources.jar",
          "url": "ppbluetoothkit-4.5.1-sources.jar",
          "size": 573271,
          "sha512": "9b2a0b4c775ed34409ef52562b730cf66df10420279ac13a04866ccd649e8bbca5777cfd17315115993f3d0332202646589182c6732dd68b42c9a1d03061521e",
          "sha256": "5644ebb2b4d2b76e7fa13297ad8c268d4a57d583b08890d4973941ff493070aa",
          "sha1": "53a9e5f5023da6b475a0e2a46a028f140da3af61",
          "md5": "1e48dcdb563a168212d7445e50955694"
        }
      ]
    }
  ]
}
