{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lefu.ppbluetoothkit",
    "module": "ppbluetoothkit",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "PPBluetoothKitDemo.ppsdkkit.lefulib",
          "module": "bluetoothkit",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "ppbluetoothkit-4.2.0.aar",
          "url": "ppbluetoothkit-4.2.0.aar",
          "size": 662013,
          "sha512": "65d8e3b36db84e6800dff0cff29af88bc6b855b0a426d199a4c0438f4018ad967f650c0daa5eebe5f7c3d062cff9875cf9c1a998002de12c49da76db6bf2ee59",
          "sha256": "9c5ce05c91b5a9298323ea4720a8fb791f287d037e1f862d077aad1532649e17",
          "sha1": "c144ad16b7e71e8099ff533fcbab385fc3e5bb4b",
          "md5": "648a8b48683358678482da3b0987e017"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "PPBluetoothKitDemo.ppsdkkit.lefulib",
          "module": "bluetoothkit",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "ppbluetoothkit-4.2.0.aar",
          "url": "ppbluetoothkit-4.2.0.aar",
          "size": 662013,
          "sha512": "65d8e3b36db84e6800dff0cff29af88bc6b855b0a426d199a4c0438f4018ad967f650c0daa5eebe5f7c3d062cff9875cf9c1a998002de12c49da76db6bf2ee59",
          "sha256": "9c5ce05c91b5a9298323ea4720a8fb791f287d037e1f862d077aad1532649e17",
          "sha1": "c144ad16b7e71e8099ff533fcbab385fc3e5bb4b",
          "md5": "648a8b48683358678482da3b0987e017"
        }
      ]
    }
  ]
}
