{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lefu.ppbluetoothkit",
    "module": "ppbluetoothkit",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "ppbluetoothkit-4.2.0.aar",
          "url": "ppbluetoothkit-4.2.0.aar",
          "size": 662013,
          "sha512": "b5f431511df555cf30ef350f60a5c94400497d418c613e2e4e8d7bdfc07bc98f3787c0f331f64cf7d8250e3a7b067841a1eef7fb2837c9d5c610ab074b89bc52",
          "sha256": "ffa1b68406dbd74a7eb0ea36ee41cf645116ead5840e27756e913b8639b9d05a",
          "sha1": "c01c46ed1d5d1f74ed6257701c239fb72b71c10f",
          "md5": "e5ca46ad3dad0a69417ff6b90ee24af4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "ppbluetoothkit-4.2.0.aar",
          "url": "ppbluetoothkit-4.2.0.aar",
          "size": 662013,
          "sha512": "b5f431511df555cf30ef350f60a5c94400497d418c613e2e4e8d7bdfc07bc98f3787c0f331f64cf7d8250e3a7b067841a1eef7fb2837c9d5c610ab074b89bc52",
          "sha256": "ffa1b68406dbd74a7eb0ea36ee41cf645116ead5840e27756e913b8639b9d05a",
          "sha1": "c01c46ed1d5d1f74ed6257701c239fb72b71c10f",
          "md5": "e5ca46ad3dad0a69417ff6b90ee24af4"
        }
      ]
    }
  ]
}
