{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lefu.ppcalculatekit",
    "module": "ppcalculatekit",
    "version": "4.2.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "ppcalculatekit-4.2.0.3.aar",
          "url": "ppcalculatekit-4.2.0.3.aar",
          "size": 660023,
          "sha512": "06826922a88f28330324967b76b2cbf487ef6a69cb605380894af051f77aa0fef8b8cf1187abc4bcabbe9b18e5fb7c302ab28ce25fd62c464bf029e4999480a0",
          "sha256": "97f995503287768ac735895b008e8c01bdf02da718a056247599573d9612f2e7",
          "sha1": "15b6ec1eb26d781bce2385fbac2fef8b7b4e6206",
          "md5": "650ec3825277de604c718568604ec751"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "ppcalculatekit-4.2.0.3.aar",
          "url": "ppcalculatekit-4.2.0.3.aar",
          "size": 660023,
          "sha512": "06826922a88f28330324967b76b2cbf487ef6a69cb605380894af051f77aa0fef8b8cf1187abc4bcabbe9b18e5fb7c302ab28ce25fd62c464bf029e4999480a0",
          "sha256": "97f995503287768ac735895b008e8c01bdf02da718a056247599573d9612f2e7",
          "sha1": "15b6ec1eb26d781bce2385fbac2fef8b7b4e6206",
          "md5": "650ec3825277de604c718568604ec751"
        }
      ]
    }
  ]
}
