{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lefu.ppcalculatekit",
    "module": "ppcalculatekit",
    "version": "4.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ppcalculatekit-4.4.1.aar",
          "url": "ppcalculatekit-4.4.1.aar",
          "size": 675662,
          "sha512": "c1663f119c596a75f1cd0b53401ba5e0fcaadf3ec03dfa9dbdf78a23ca11eb6934b8ced09ad03b2d2ca2b38aad02afb490ee05b60543356c401d8e2258d23274",
          "sha256": "edfddddc6264b010f3862e38dc2982e67e632170b67d67014733f1ec541c7fc4",
          "sha1": "abcc717563a3a5f9531b7a1f87079e0f508c5d5c",
          "md5": "b0be84999f80f8be14076d013cde4ff1"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ppcalculatekit-4.4.1.aar",
          "url": "ppcalculatekit-4.4.1.aar",
          "size": 675662,
          "sha512": "c1663f119c596a75f1cd0b53401ba5e0fcaadf3ec03dfa9dbdf78a23ca11eb6934b8ced09ad03b2d2ca2b38aad02afb490ee05b60543356c401d8e2258d23274",
          "sha256": "edfddddc6264b010f3862e38dc2982e67e632170b67d67014733f1ec541c7fc4",
          "sha1": "abcc717563a3a5f9531b7a1f87079e0f508c5d5c",
          "md5": "b0be84999f80f8be14076d013cde4ff1"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ppcalculatekit-4.4.1-sources.jar",
          "url": "ppcalculatekit-4.4.1-sources.jar",
          "size": 105625,
          "sha512": "c4f2d37630d895aeedc59cceb55d8cbaa43747b90b799e2211f3b220eb675e6575bf36e47e3403c149cdfb8140d922187302944c1a9a895d817c01f947e1545d",
          "sha256": "9c9f4496796f4b2246c6dabe0e368e7ef795da98f1393c9bdfae899914313923",
          "sha1": "16fbd03ba9726723a66e8edaed0e9082d5bdad80",
          "md5": "663da3b0731f2a916557affaed420304"
        }
      ]
    }
  ]
}
