{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lefu.ppbasekit",
    "module": "ppbasekit",
    "version": "4.5.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ppbasekit-4.5.0.aar",
          "url": "ppbasekit-4.5.0.aar",
          "size": 248888,
          "sha512": "996ab6756323014b8cfb4d4d11faf183441c21a0ced7e92fe0e9411ef9cabdf23519b96e457c31e3c021ba393cf5b1f6f4fffd7f6a1a0b0e0aeba88493d94317",
          "sha256": "aca2407d8ea056153ed315487964832a36290a503594fad9f4f927de804552ad",
          "sha1": "0bd398f91dede096eff2f67eecf2b8228c37ffe2",
          "md5": "ad43c54fc814742eb4d6e5eda11c7960"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ppbasekit-4.5.0.aar",
          "url": "ppbasekit-4.5.0.aar",
          "size": 248888,
          "sha512": "996ab6756323014b8cfb4d4d11faf183441c21a0ced7e92fe0e9411ef9cabdf23519b96e457c31e3c021ba393cf5b1f6f4fffd7f6a1a0b0e0aeba88493d94317",
          "sha256": "aca2407d8ea056153ed315487964832a36290a503594fad9f4f927de804552ad",
          "sha1": "0bd398f91dede096eff2f67eecf2b8228c37ffe2",
          "md5": "ad43c54fc814742eb4d6e5eda11c7960"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ppbasekit-4.5.0-sources.jar",
          "url": "ppbasekit-4.5.0-sources.jar",
          "size": 38661,
          "sha512": "ee9c4ee9c9e24010389307069863b25b47abfa3b7ef86fda056854778da015980684dea7b6f77c09a049f46f49c6748609ba92887a10c77a5e4656bd27bbadfe",
          "sha256": "9a5b8ca82cfe26b54a4d0e3635702391d80a7cec15dbf5ab34b19b5578bd5626",
          "sha1": "daee12c316fd3edf5a212b117f08a0c25cd80b39",
          "md5": "2cc6935ef871cd99fa1894fa22441e76"
        }
      ]
    }
  ]
}
