{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lefu.ppcalculatekit",
    "module": "ppcalculatekit",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "ppcalculatekit-4.2.0.aar",
          "url": "ppcalculatekit-4.2.0.aar",
          "size": 660023,
          "sha512": "af4ee1847f784d19fc56e84bb5da1b22569afcf8bc533e2c69d7a3dfc12df5e91bb1da1e53251e78935975e2e9b7dbddd983da6a9051719de90c413f43b3f565",
          "sha256": "83262a22bd0c69ed98c6ee7202cc3cd99eed52d07b933242d25474987eaaecd9",
          "sha1": "6453f1fdd0e68f305eecb03ab9965bff1da7a536",
          "md5": "dbeab1d90c9911175f9c1bffebeda8e4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "ppcalculatekit-4.2.0.aar",
          "url": "ppcalculatekit-4.2.0.aar",
          "size": 660023,
          "sha512": "af4ee1847f784d19fc56e84bb5da1b22569afcf8bc533e2c69d7a3dfc12df5e91bb1da1e53251e78935975e2e9b7dbddd983da6a9051719de90c413f43b3f565",
          "sha256": "83262a22bd0c69ed98c6ee7202cc3cd99eed52d07b933242d25474987eaaecd9",
          "sha1": "6453f1fdd0e68f305eecb03ab9965bff1da7a536",
          "md5": "dbeab1d90c9911175f9c1bffebeda8e4"
        }
      ]
    }
  ]
}
