{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lefu.ppbasekit",
    "module": "ppbasekit",
    "version": "4.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "PPBluetoothKitDemo2.ppsdkkit.lefulib",
          "module": "lfgson",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ppbasekit-4.4.0.aar",
          "url": "ppbasekit-4.4.0.aar",
          "size": 50795,
          "sha512": "85ca0e8905e691caea5e9f6eec183e9bf58a5a8f7a9e9e44320830d06dee2a9bd9d9de77f2fe1b95825078d22fe70ca9c96f6a893243ddcc928b5126842f4a7a",
          "sha256": "575ec4821414734e1b70988e2d51efa5127c1760ee306c715f1704328fdf5728",
          "sha1": "ea3bea192ef5f0c07cebd2371ba6ca257b07a948",
          "md5": "3ac57ad5806f3fcdd0ca6f6057d620bf"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "PPBluetoothKitDemo2.ppsdkkit.lefulib",
          "module": "lfgson",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ppbasekit-4.4.0.aar",
          "url": "ppbasekit-4.4.0.aar",
          "size": 50795,
          "sha512": "85ca0e8905e691caea5e9f6eec183e9bf58a5a8f7a9e9e44320830d06dee2a9bd9d9de77f2fe1b95825078d22fe70ca9c96f6a893243ddcc928b5126842f4a7a",
          "sha256": "575ec4821414734e1b70988e2d51efa5127c1760ee306c715f1704328fdf5728",
          "sha1": "ea3bea192ef5f0c07cebd2371ba6ca257b07a948",
          "md5": "3ac57ad5806f3fcdd0ca6f6057d620bf"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ppbasekit-4.4.0-sources.jar",
          "url": "ppbasekit-4.4.0-sources.jar",
          "size": 38445,
          "sha512": "d738479e591008f016ab2358fb39a7549863a7c4cbf84063e88abc8c4cce4b60636c2c3862bf48b04daf2b595b44a7edd5a4d4b833e67acc0b86d633a101b685",
          "sha256": "5fa698522d933784d1f1cb63c15f6efca468e3b24708814663407424d2ac659c",
          "sha1": "6b40f44d51857e8c28b99d8dc0457302d620b2a2",
          "md5": "d2c3308bbc0ae99375e6d8830796cd6b"
        }
      ]
    }
  ]
}
