{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lefu.ppcalculatekit",
    "module": "ppcalculatekit",
    "version": "4.2.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "ppcalculatekit-4.2.0.1.aar",
          "url": "ppcalculatekit-4.2.0.1.aar",
          "size": 660023,
          "sha512": "6d1ddc8c8a22864262acb6d490452d63cefefd4f51b3d74d4f510f5a0067fd6fe96a6795dcbd07707d6501ed41716bab10cae87e23a47ad0a762157de92685b6",
          "sha256": "462c44dd43049f73a8e6d4722c301b66662bcf6e0e4fbd6231c0e93289d85abe",
          "sha1": "95cbc5bbd8568f273c66ef2184f7a710d076d902",
          "md5": "5cfd415128c0e5b6f1615318c0791442"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.8"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.21"
          }
        }
      ],
      "files": [
        {
          "name": "ppcalculatekit-4.2.0.1.aar",
          "url": "ppcalculatekit-4.2.0.1.aar",
          "size": 660023,
          "sha512": "6d1ddc8c8a22864262acb6d490452d63cefefd4f51b3d74d4f510f5a0067fd6fe96a6795dcbd07707d6501ed41716bab10cae87e23a47ad0a762157de92685b6",
          "sha256": "462c44dd43049f73a8e6d4722c301b66662bcf6e0e4fbd6231c0e93289d85abe",
          "sha1": "95cbc5bbd8568f273c66ef2184f7a710d076d902",
          "md5": "5cfd415128c0e5b6f1615318c0791442"
        }
      ]
    }
  ]
}
